### ISSUE TITLE
alignment of collapse button and light/dark mode button

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#162]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AshleshaKawale** [comment]
@maithililondhewaiin  Remove the Outer Line for the Light Mode.
![image](https://user-images.githubusercontent.com/109782676/185596539-b95a20f2-2f9d-4dab-a7d4-523a5b15ea38.png)
