### ISSUE TITLE
Users>>Roles>>Edit>>Not able to add new users after clicking outside the offcanvas.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#200]
**Describe the bug**
Users>>Roles>>Edit>>After clicking outside the offcanvas when click on new users again still showing edit users screen.

**To Reproduce**
1. Go to '..users.'
2. Click on '..Edit, click on outside off canvas...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AshleshaKawale** [comment]
![Image](https://user-images.githubusercontent.com/109782676/188141433-457aee50-5c23-4dc6-b24b-9683a02c8cb0.png)

Showing the Validation for the User name. if only name is entered and then clicked outside the off canvas and then again click on new user
