### ISSUE TITLE
Languages << Watermark for Country Code.

### ISSUE THREAD

**Issue by AshleshaKawale** [Wai-Technologies/raaghu-angular#316]
**Describe the bug**
Languages << Watermark for Country Code. 
**To Reproduce**
1. Go to 'stageui.raaghu.io'
2. Click on 'languages'
3. Scroll down to 'New Language'

**Expected behavior**
Languages << New Language : Remove the duplicate text in the select language

**Screenshots**
![image](https://user-images.githubusercontent.com/109782676/186887904-9cc76eeb-0f84-401e-a8f9-ba7a5cce90eb.png)

**Comment by adilsayyad** [comment]
@vyankatesh21 
Critical bug need to assign to senior developer

**Comment by neeraj-bhakre** [comment]
Won't fixed, because data coming from API.
