### ISSUE TITLE
Host admin>>Theming issues.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#514]
![image](https://user-images.githubusercontent.com/109503161/190132514-b2a78a10-a883-4384-9b17-99925bfc53b1.png)

**Comment by rahulp34** [comment]
verified with attached screenshot



![Image](https://user-images.githubusercontent.com/55730676/201588079-334f34fc-e254-4c3b-9ced-d92a0ae75f9b.png)
