### ISSUE TITLE
Storybook>>product overview all stories>>14 Days return policy and Cash on delivery available icons is not rendering.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#733]
![Image](https://user-images.githubusercontent.com/109503161/195840308-e5bb8bdf-a94e-4516-9120-372942223459.png)

**Comment by rohit9096** [comment]
![Image](https://user-images.githubusercontent.com/88035057/195839677-d2af27a8-f6db-459a-81e7-f24b2d23c723.png)
