### ISSUE TITLE
Host admin>>Off canvas>>Manage authority delegations>>Alignment issues.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#810]
Hand cursor should be there for date picker.

Actual result:

![Image](https://user-images.githubusercontent.com/109503161/197110514-799979b4-f046-48aa-9486-354c580cd44e.png)

Expected result:

![Image](https://user-images.githubusercontent.com/109503161/197110665-87c58538-c0db-4027-bad0-abd28a0d4810.png)

**Comment by rahulp34** [comment]
verified with attached screenshots



![Image](https://user-images.githubusercontent.com/55730676/201587771-e4697537-bc92-4bd2-98f1-f716b90d378a.png)

and hand cursor also present for hand cursor
