### ISSUE TITLE
Host admin>>Off canvas>>Need some spacing and remove extra border line.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#849]
Expected result:
https://xd.adobe.com/view/ef317bf7-094c-47f8-87ea-fb53f1e192a3-ba62/screen/75113d94-2924-47bc-a91e-1583e3867b38/

![Image](https://user-images.githubusercontent.com/109503161/199156343-4ba140e6-0f8c-4d16-a7b8-d32768e04083.png)

**Comment by rahulp34** [comment]
Verified with attached screenshot




![Image](https://user-images.githubusercontent.com/55730676/201624942-5d2e5541-02e7-433a-bed5-d56256d96063.png)
