### ISSUE TITLE
Host admin>>Left navigation menu>>After refreshing page accordion is closing.

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-angular#851]
Before refreshing

![Image](https://user-images.githubusercontent.com/109503161/199157249-ab93435c-c3ff-40aa-9bf1-cf1b338d9d3a.png)

After refreshing 

![Image](https://user-images.githubusercontent.com/109503161/199157277-b2a6c833-ca36-4ea0-82a0-11a3e801250c.png)

**Comment by rahulp34** [comment]
verified!

screenshots attached

Before refreshing



![Image](https://user-images.githubusercontent.com/55730676/201587442-b86a0720-a92f-4755-98a0-ce7b907d98f8.png)

after refreshing



![Image](https://user-images.githubusercontent.com/55730676/201587515-862234ef-e49d-4433-94eb-2733aff700d1.png)
